<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PrestaKit.Extensions.DependencyInjection\PrestaKit.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\PrestaKit\PrestaKit.csproj" />
    <ProjectReference Include="..\..\tests\PrestaKit.IntegrationTests\PrestaKit.IntegrationTests.csproj" />
  </ItemGroup>

</Project>
