<Project Sdk="Microsoft.NET.Sdk">

	<!-- Package identity -->
	<PropertyGroup>
		<PackageId>PrestaKit.Extensions.DependencyInjection</PackageId>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PrestaKit\PrestaKit.csproj" />
	</ItemGroup>

</Project>
