<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageId>PrestaKit</PackageId>
		<Version>0.2.0</Version>
		<PackageIcon>logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\..\assets\logo.png" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
